/* This file automatically generated by xml2src.py        */
/* Do not edit this file directly, changes will be lost   */
#include <stdlib.h>
#include "doctext.h"


/* Text for each of the help entries                      */
/**********************************************************/

const char* PATHDB_HELP_ENTRIES[] = {
   /* Begin entry: help */
   "This is the Help system for the PathScale Debugger (pathdb).\n"
   "Type \'help\' followed by a topic or command name. Help is\n"
   "available for the following topics:\n"
   "   1. Breakpoints - Information on breakpoints\n"
   "   2. Running - How to run the program\n"
   "   3. Locations - How to specify locations used by\n"
   "   some commands.\n"
   "   4. Commands - Information on all the commands\n"
   "   available\n"
   "   5. Formats - Formats for the print function\n"
   "   6. Expressions - Expression support\n"
   "   7. Parameters - Debugger parameters\n"
   "Note that the first letter is uppercase, to\n"
   "distinguish the topic from a command of the same name.\n"
   ,/* End entry: help */

   /* Begin entry: Breakpoints */
   "Breakpoints are special instructions inserted into\n"
   "the program by the debugger that make the program\n"
   "stop when executed. A breakpoint is inserted at a\n"
   "particular address. When the program hits a breakpoint,\n"
   "the debugger gains control of the program and\n"
   "typically returns to the command prompt, allowing\n"
   "the user to issue commands to control the program.\n"
   "\n"
   "Breakpoints are usually set by use of the \'break\'\n"
   "command, but other commands exist to set different\n"
   "types of breakpoints. The following commands are\n"
   "available for setting and manipulating breakpoints:\n"
   "\n"
   "   1. break - Set a software breakpoint\n"
   "   2. hbreak - Set a hardware breakpoint\n"
   "   3. tbreak - Set a temporary breakpoint\n"
   "   4. thbreak - Set a temporary hardware breakpoint\n"
   "   5. watch - Set a write watchpoint\n"
   "   6. awatch - Set an access watchpoint\n"
   "   7. rwatch - Set a read watchpoint\n"
   "   8. catch - Set a catchpoint\n"
   "   9. commands - Set the commands for a breakpoint\n"
   "   10. condition - Set the condition for a breakpoint\n"
   "   11. ignore - Set the ignore count for a breakpoint\n"
   "   12. delete - Delete breakpoints based on breakpoint number\n"
   "   13. clear - Delete breakpoints based on location\n"
   "   14. disable - Disable breakpoints\n"
   "   15. enable - Enable breakpoints\n"
   "   16. info breakpoints - Get information on breakpoints\n"
   "Breakpoints, watchpoints, and catchpoints can all be conditional and\n"
   "can execute a set of commands when triggered.\n"
   ,/* End entry: Breakpoints */

   /* Begin entry: Running */
   "The debugger works by attaching itself to a process\n"
   "containing the program being debugged. When attached,\n"
   "the debugger lets the user control the program by\n"
   "issuing commands. The following commands are available\n"
   "for controlling the program:\n"
   "   1. run - Start or restart the program\n"
   "   2. rerun - Rerun the program by restarting and\n"
   "   replaying commands\n"
   "   3. kill - Kill the program currently being\n"
   "   debugged\n"
   "   4. step - Step a number of lines, stepping\n"
   "   into functions\n"
   "   5. next - Step a number of lines, stepping\n"
   "   over function calls\n"
   "   6. continue - Continue execution of the\n"
   "   program\n"
   ,/* End entry: Running */

   /* Begin entry: Locations */
   "Locations can be specified as follows:\n"
   "   1. An address, specified by a \'*\' followed by an expression\n"
   "   2. A function name, optionally enclosed in quotes\n"
   "   3. A filename followed by a colon, then a line number of\n"
   "   function name\n"
   "   4. A number representing a line number in the current file\n"
   "In addition, some commands (like \'list\') accept a \'+\' or \'-\' sign\n"
   "followed by a number. This means + or - a number of lines.\n"
   "\n"
   ,/* End entry: Locations */

   /* Begin entry: Commands */
   "The following commands are available. Type \'help\'\n"
   "followed by the command name for information on\n"
   "that command.\n"
   ,/* End entry: Commands */

   /* Begin entry: Formats */
   "Certain commands (\'print\', \'output\', \'call\', \'display\'\n"
   "and \'x\') can take a format specifier as their first\n"
   "argument.  If this is present, it must be prefixed by\n"
   "a \'/\' character.\n"
   "\n"
   "The syntax of the format specifier as used with print is:\n"
   "print /[count][code][size] (no spaces are allowed)\n"
   "\n"
   "The \'count\' specifier is a decimal number specifying\n"
   "the number of elements to which this format applies.\n"
   "The \'code\' specifies the output format for the elements.\n"
   "The \'size\' specifies the size of each element.\n"
   "\n"
   "The \'code\' is specified by a single lowercase letter.  Allowed codes are:\n"
   "   1. \'o\' - octal\n"
   "   2. \'x\' - hexadecimal\n"
   "   3. \'d\' - decimal\n"
   "   4. \'u\' - unsigned decimal\n"
   "   5. \'t\' - binary\n"
   "   6. \'f\' - floating point\n"
   "   7. \'a\' - address\n"
   "   8. \'c\' - character\n"
   "   9. \'s\' - string\n"
   "   10. \'i\' - instruction disassembly\n"
   "The size is also specified by a single lowercase letter:\n"
   "   1. \'b\' - byte (8 bits)\n"
   "   2. \'h\' - half word (16 bits)\n"
   "   3. \'w\' - word (32 bits)\n"
   "   4. \'g\' - giant word (64 bits)\n"
   ,/* End entry: Formats */

   /* Begin entry: Expressions */
   "The PathScale debugger has extensive support for\n"
   "expressions in both C (and C++) and Fortran 90 languages.\n"
   "The expression parser is context sensitive and thus\n"
   "depends on which language the current function is\n"
   "written in.\n"
   "\n"
   "The highest priority is the \'primary\' expression\n"
   "which consists of:\n"
   "   1. (expression)\n"
   "   2. identifier [@ line-number]\n"
   "   3. number (integer or floating point)\n"
   "   4. \"string\" or \'string\'\n"
   "   5. \'character\'\n"
   "   6. $regname or $debug_var\n"
   "   7. {vector literal, ...}\n"
   "   8. type specification\n"
   "The syntax \'identifier @ line-number\' allows a way\n"
   "to distinguish among variables with the same name\n"
   "in nested lexical scopes. All identifiers are\n"
   "case-sensitive.\n"
   "\n"
   "Numbers are in the standard C syntax (prefix 0 for octal,\n"
   "0x for hex). No suffixes are supported at present.\n"
   "\n"
   "The postfix \'()\' operator allows functions to be called\n"
   "in the program being debugged. The array subscripting\n"
   "operator \'[]\' allows a range to be specified using a\n"
   "\':\' to separate the lower and upper bounds of the\n"
   "range (e.g. print foo[3:5])\n"
   "\n"
   "Note that some of the operators available in Fortran mode are\n"
   "strictly not Fortran operators, but are useful for debugger\n"
   "functionality.\n"
   "\n"
   "The highest priority is the \'primary expression\', which is\n"
   "one of:\n"
   "   1. (expression)\n"
   "   2. intrinsic\n"
   "   3. identifier [@ line-number]\n"
   "   4. $regname\n"
   "   5. $debug_var\n"
   "   6. number (in Fortran syntax)\n"
   "   7. \'string\' or \"string\"\n"
   "   8. \'character\'\n"
   "   9. .true. or .false.\n"
   "   10. {vector literal, ...}\n"
   "Numbers are in both C and Fortran syntax, so both 0x and \'Z can\n"
   "be used to specify a hex number. All identifiers are case-blind.\n"
   "\n"
   "The intrinsics supported are:\n"
   "   1. KIND()\n"
   "   2. LOC()\n"
   "   3. ALLOCATED()\n"
   "   4. ASSOCIATED()\n"
   "   5. UBOUND()\n"
   "   6. LBOUND()\n"
   "   7. LEN()\n"
   "   8. SIZE()\n"
   "   9. ADDR()\n"
   "Both C/C++ and Fortran expressions support type casts. The\n"
   "syntax of the type is language dependent. The following\n"
   "are examples of type casts in C and Fortran:\n"
   "\n"
   "print (const int *)foo                   - C\n"
   "print (integer(kind=8), pointer)bar      - Fortran\n"
   ,/* End entry: Expressions */

   /* Begin entry: Parameters */
   "Parameters are variables that control the behavior of the debugger.  They\n"
   "are set using the \'set\' command and shown using the \'show\' command.  Here\n"
   "are the default values of the supported parameters.\n"
   "\n"
   "args:  Argument list to give to program is \"\".\n"
   "can-use-hw-watchpoints:  Ability to use hardware watchpoints is 1.\n"
   "confirm:  Confirmation of dangerous commands is on.\n"
   "endian:  The target endianness is \"auto\" (currently little endian).\n"
   "follow-fork-mode:  What to do with fork is \"parent\".\n"
   "frame-debug:  Debug stack frame debugger code is off.\n"
   "height:  Height of the window is 42.\n"
   "language:  The current language is \"auto\" (currently c).\n"
   "listsize:  Number of lines to list is 10.\n"
   "multi-process:  Handle multiple processes is off.\n"
   "pagination:  Whether to stop at end of page is on.\n"
   "print address:  Printing of addresses is on.\n"
   "print array:  Pretty printing of arrays is on.\n"
   "print elements:  Limit on string chars or array elements to print is 200.\n"
   "print null-stop:  Printing of char arrays to stop at first null char is off.\n"
   "print object:  Printing of dynamic object types is on.\n"
   "print pretty:  Pretty printing of structures is on.\n"
   "print repeats:  Threshold for repeated print elements is 10.\n"
   "print sevenbit-strings:  Printing of 8-bit characters in strings as \\nnn is on.\n"
   "print sigdigits:  Number of significant digits for floating point values is 10.\n"
   "print simplify-template:  Simplification of templates in printing is on.\n"
   "print static-members:  Printing of C++ static members is on.\n"
   "print std-list:  Printing of std::list is on.\n"
   "print std-map:  Printing of std::map is on.\n"
   "print std-string:  Printing of std::string is on.\n"
   "print std-vector:  Printing of std::vector is on.\n"
   "print union:  Printing of union members is on.\n"
   "prompt:  The prompt is \"pathdb> \".\n"
   "shell-mode:  Unknown commands invoked as shell command is on.\n"
   "stop-on-solib-events:  Stopping for shared library events is 0.\n"
   "thread-debug:  Debug thread debugger code is off.\n"
   "width:  Width of the window is 124.\n"
   "\n"
   "\n"
   "If the \'set\' command is used to set the value of an unknown\n"
   "parameter, it will try to set the value of a variable in the\n"
   "program.\n"
   "\n"
   "Examples of setting parameter values:\n"
   "\n"
   "set elements 300\n"
   "set confirm off\n"
   "set pretty\n"
   "set prompt (pathdb)\n"
   "\n"
   "\n"
   "Most parameters are similar to the parameter of the same name in GDB.  A\n"
   "few of the new ones are:\n"
   "   1. follow-fork-mode - Can be \"both\" to follow parent and child\n"
   "   2. multi-process - When on, the debugger will track multiple\n"
   "   processes\n"
   "   3. frame-debug - When on, print internal debug information for\n"
   "   stack frames\n"
   "   4. print simplify-template - When on, standard templates are\n"
   "   simplified for ease of reading\n"
   "   5. print std-list - When on, the contents std::list objects\n"
   "   are printed\n"
   "   6. print std-vector - When on, the contents std::vector objects\n"
   "   are printed\n"
   "   7. print std-map - When on, the contents std::map objects\n"
   "   are printed\n"
   "   8. print std-string - When on, the contents std::string\n"
   "   objects are printed\n"
   "   9. shell-mode - When on, all unknown commands are passed\n"
   "   directly to the shell\n"
   "   10. thread-debug - When on, print internal debugger debug\n"
   "   information about threads\n"
   ,/* End entry: Parameters */

   /* Begin entry: advance */
   "Command advance: Continue execution until the specified location is reached.\n"
   ,/* End entry: advance */

   /* Begin entry: alias */
   "Command alias: With no args, show all aliases.  With one arg, show the named\n"
   "alias.  With two args, set the named alias to the named value.\n"
   "This command lets you define aliases for other commands.  To\n"
   "list the defined aliases, omit the arguments.  To show the\n"
   "definition of a defined alias, give its name as the only\n"
   "argument.  To define a new alias, provide the name of the\n"
   "alias as the first argument and its definition as the second.\n"
   "\n"
   "See Also:\n"
   "define,unalias\n"
   ,/* End entry: alias */

   /* Begin entry: attach */
   "Command attach: Attach to a running process.\n"
   "Attach the debugger to a running process. Give the process id\n"
   "as the argument. The process must be owned by the current\n"
   "user and be running. The debugger attaches to the process and\n"
   "stops it running, thus allowing it to be debugged.  To detach\n"
   "from the process and let it continue, use the detach command\n"
   "or quit the debugger.\n"
   "\n"
   "See Also:\n"
   "detach\n"
   ,/* End entry: attach */

   /* Begin entry: backtrace */
   "Command backtrace: Show the stack backtrace for the specified number of\n"
   "levels (Default: all levels).\n"
   "Print the functions through which the program has progressed to\n"
   "reach the current point. Each function is known as a \'frame\'.\n"
   "For each frame (starting at main), the debugger prints the value\n"
   "of the program counter, the name of the function (if known), the\n"
   "function arguments and their values, and finally the source file\n"
   "and line number (if known). The topmost frame is printed first\n"
   "and is numbered #0.\n"
   "\n"
   "The following is an example of a backtrace command:\n"
   "\n"
   "pathdb> backtrace\n"
   "=>#0  AN.in.EXP1 (t=1, x=1, n=1) at /home/dallison/bk/pathdb/src/exp1.f:27\n"
   "#1  0x0000000000400c04 in MAIN__ () at /home/dallison/bk/pathdb/src/exp1.f:10\n"
   "#2  0x00000000004010cc in __f90_main ()\n"
   "#3  0x00000000004010a4 in main ()\n"
   "\n"
   "The current frame is marked with \'=>\'.  You can use the \'up\' and\n"
   "\'down\' commands to change the current frame.\n"
   "\n"
   "See Also:\n"
   "up,down,frame\n"
   ,/* End entry: backtrace */

   /* Begin entry: break */
   "Command break: Set a breakpoint at the specified location.\n"
   "Set a breakpoint at a location.  The location is\n"
   "specified by:\n"
   "   1. A * followed by an address\n"
   "   2. A line number in the current file\n"
   "   3. A filename and line number, specified by\n"
   "   filename:lineno\n"
   "   4. A function name\n"
   "The result will be a breakpoint inserted at the given address\n"
   "in the program. If the address cannot be determined, the\n"
   "option to create a \'pending breakpoint\' will be given.\n"
   "The debugger will try to resolve pending breakpoints to\n"
   "addresses whenever a shared library is loaded.\n"
   "\n"
   "If the function name given to the command is ambiguous,\n"
   "a menu of alternative functions will be presented.\n"
   "This is particularly useful for C++ member functions.\n"
   "For example:\n"
   "\n"
   "pathdb> b evaluate\n"
   "Choose one of the following functions:\n"
   "0.  cancel\n"
   "1.  CallExpression::evaluate\n"
   "2.  ArrayExpression::evaluate\n"
   "a.  all\n"
   "\n"
   "The command may be followed by the following clauses:\n"
   "   1. if <expression> - set a condition for the\n"
   "   breakpoint\n"
   "   2. thread <thread-num> - activate breakpoint\n"
   "   for the specific thread\n"
   "\n"
   "See Also:\n"
   "watch,hbreak,tbreak,catch,rwatch,awatch,commands,condition\n"
   ,/* End entry: break */

   /* Begin entry: call */
   "Command call: Call a function in the program being debugged. Record\n"
   "the value and print it if the type is not void.\n"
   "Cause the program to execute the given expression.  Typically,\n"
   "the expression will be a function call.  The program being\n"
   "debugged executes the expression and if the result is\n"
   "non-void, the debugger prints the result and inserts it into\n"
   "the value history.\n"
   "\n"
   "The number of arguments passed to the function must match those\n"
   "defined for the function.  If the function being called is one of\n"
   "a set of C++ overloads, the types of the arguments will be used to\n"
   "determine which overload to call.\n"
   "\n"
   "See Also:\n"
   "print,output\n"
   ,/* End entry: call */

   /* Begin entry: catch catch */
   "Command catch: Catch C++ exception catches.\n"
   "Create a catchpoint that will be activate\n"
   "when a C++ exception is caught.\n"
   ,/* End entry: catch catch */

   /* Begin entry: catch exec */
   "Command exec: Catch calls to exec system call.\n"
   ,/* End entry: catch exec */

   /* Begin entry: catch exit */
   "Command exit: Catch calls to exit.\n"
   ,/* End entry: catch exit */

   /* Begin entry: catch fork */
   "Command fork: Catch a call to fork.\n"
   ,/* End entry: catch fork */

   /* Begin entry: catch load */
   "Command load: Catch loads of shared libraries.\n"
   ,/* End entry: catch load */

   /* Begin entry: catch print */
   "Command print: Not implemented.\n"
   ,/* End entry: catch print */

   /* Begin entry: catch start */
   "Command start: Not implemented.\n"
   ,/* End entry: catch start */

   /* Begin entry: catch signal */
   "Command signal: Not implemented.\n"
   ,/* End entry: catch signal */

   /* Begin entry: catch stop */
   "Command stop: Not implemented.\n"
   ,/* End entry: catch stop */

   /* Begin entry: catch thread_exit */
   "Command thread_exit: Not implemented.\n"
   ,/* End entry: catch thread_exit */

   /* Begin entry: catch thread_join */
   "Command thread_join: Not implemented.\n"
   ,/* End entry: catch thread_join */

   /* Begin entry: catch thread_start */
   "Command thread_start: Not implemented.\n"
   ,/* End entry: catch thread_start */

   /* Begin entry: catch throw */
   "Command throw: Catch C++ exception throws.\n"
   ,/* End entry: catch throw */

   /* Begin entry: catch unload */
   "Command unload: Not implemented.\n"
   ,/* End entry: catch unload */

   /* Begin entry: catch vfork */
   "Command vfork: Not implemented.\n"
   ,/* End entry: catch vfork */

   /* Begin entry: catch */
   "Command catch: Show the expressions that can be caught\n"
   "in the current function.\n"
   "Insert a catchpoint into the program being\n"
   "debugged. A catchpoint is a special breakpoint\n"
   "that is set to trigger on certain events.\n"
   "\n"
   "Subcommands:\n"
   "catch catch: Catch C++ exception catches.\n"
   "catch exec: Catch calls to exec system call.\n"
   "catch exit: Catch calls to exit.\n"
   "catch fork: Catch a call to fork.\n"
   "catch load: Catch loads of shared libraries.\n"
   "catch print: Not implemented.\n"
   "catch start: Not implemented.\n"
   "catch signal: Not implemented.\n"
   "catch stop: Not implemented.\n"
   "catch thread_exit: Not implemented.\n"
   "catch thread_join: Not implemented.\n"
   "catch thread_start: Not implemented.\n"
   "catch throw: Catch C++ exception throws.\n"
   "catch unload: Not implemented.\n"
   "catch vfork: Not implemented.\n"
   ,/* End entry: catch */

   /* Begin entry: cd */
   "Command cd: Change the current working directory to that\n"
   "specified. No arguments means to change to\n"
   "the home directory.\n"
   "The current directory is changed for the debugger\n"
   "to that given. Tilde expansions are performed.\n"
   "\n"
   "See Also:\n"
   "pwd\n"
   ,/* End entry: cd */

   /* Begin entry: clear */
   "Command clear: Clear breakpoints at the specified location\n"
   "(line or address). If no location is specified,\n"
   "it clears the breakpoint at the current locations.\n"
   "Clear any breakpoints that are set at the specified\n"
   "location. The location may be specified by:\n"
   "   1. An empty argument list, meaning the current\n"
   "   location\n"
   "   2. A * followed by an address\n"
   "   3. A line number\n"
   "   4. A file name and line number, specified by\n"
   "   filename:lineno\n"
   "   5. A function name\n"
   "Like the \'break\' command, a menu of functions\n"
   "will be presented if the function name is\n"
   "ambiguous.\n"
   "\n"
   "See Also:\n"
   "delete,break\n"
   ,/* End entry: clear */

   /* Begin entry: commands */
   "Command commands: Specify a set of commands to be executed when\n"
   "the breakpoint is activated. If no breakpoint\n"
   "is specified, the last one set is targeted.\n"
   "This command allows a set of commands to be\n"
   "attached to a breakpoint. If the breakpoint is\n"
   "activated, the set of commands will be executed,\n"
   "in sequence.  If the first command is \'silent\'\n"
   "then the breakpoint will not print its information\n"
   "when activated.\n"
   "\n"
   "The commands are entered, one line at a time,\n"
   "ending with the word \'end\' on a line by itself.\n"
   "If the argument list to the command is empty,\n"
   "the last breakpoint set will be used.\n"
   "\n"
   "See Also:\n"
   "break,condition,ignore\n"
   ,/* End entry: commands */

   /* Begin entry: condition */
   "Command condition: Set or clear the condition on the specified breakpoint.\n"
   "Set the conditions for the activation of the\n"
   "breakpoint. The condition is an expression in the\n"
   "syntax of the current language that is evaluated in\n"
   "the context of the breakpoint.  If the expression\n"
   "evaluates to a non-zero value, then the breakpoint\n"
   "is activated when hit.\n"
   "\n"
   "For example:\n"
   "pathdb> condition 12 i < 4 || is_valid(j)\n"
   "\n"
   "See Also:\n"
   "break,commands,ignore\n"
   ,/* End entry: condition */

   /* Begin entry: continue */
   "Command continue: Continue execution of the program being debugged.\n"
   "If a signal number is specified, continue executing\n"
   "by sending specified signal.\n"
   "This command causes the program being debugged to\n"
   "continue execution. If an argument is passed, it\n"
   "is a signal number that is sent to the program,\n"
   "otherwise no signal is sent.  The program will\n"
   "continue execution until either stopped by a\n"
   "breakpoint, interrupted by the user, or it\n"
   "completes.\n"
   "\n"
   "See Also:\n"
   "step,next,run\n"
   ,/* End entry: continue */

   /* Begin entry: define */
   "Command define: Define a new command as a sequence of existing\n"
   "commands.\n"
   "This command allows a new command to be defined.\n"
   "Unlike the \'alias\' command, this  new command can\n"
   "contain multiple commands and arguments.  The\n"
   "arguments are specified by use of the special token\n"
   "$arg followed by a number.  There can be up to 10\n"
   "arguments passed and are named $arg0 to $arg9.\n"
   "\n"
   "The command contents are entered, one line at a\n"
   "time, terminating with \'end\' by itself.\n"
   "\n"
   "See Also:\n"
   "alias\n"
   ,/* End entry: define */

   /* Begin entry: delete breakpoints */
   "Command breakpoints: Delete all breakpoints\n"
   "Delete all the breakpoints from the program.\n"
   ,/* End entry: delete breakpoints */

   /* Begin entry: delete */
   "Command delete: Delete breakpoints, watchpoints, or displays.\n"
   "The \'delete\' command is usually used to delete\n"
   "breakpoints, but it can also be used to delete other\n"
   "things. If it is used without an argument, it means\n"
   "\'breakpoints\'\n"
   "\n"
   "Subcommands:\n"
   "delete breakpoints: Delete all breakpoints\n"
   ,/* End entry: delete */

   /* Begin entry: detach */
   "Command detach: Detach from a running process that is currently\n"
   "being controlled by the debugger.\n"
   "See Also:\n"
   "attach,file\n"
   ,/* End entry: detach */

   /* Begin entry: dir */
   "Command dir: Set the search directory for source file searches.\n"
   "This command allows a directory to be added to the\n"
   "list of those searched for source files. Modern\n"
   "compilers try to be as helpful as possible by\n"
   "inserting the names of directories into the debug\n"
   "output, but sometimes this is not sufficient to\n"
   "allow the debugger to find the file.\n"
   "\n"
   "Without an argument, the \'dir\' command sets the\n"
   "directory search path to the default.\n"
   ,/* End entry: dir */

   /* Begin entry: disable */
   "Command disable: Disable the numbered breakpoints.\n"
   ,/* End entry: disable */

   /* Begin entry: disassemble */
   "Command disassemble: Disassemble the object code in the specified address\n"
   "range. If no start or stop address is specified, the\n"
   "current function is disassembled.\n"
   "The disassemble command shows an assembly language\n"
   "listing around the specified address. The command can\n"
   "take 0, 1, or 2 arguments. When no arguments are supplied,\n"
   "the previous address disassembled, or the current address\n"
   "is used. With 1 argument, the function containing the\n"
   "address is disassembled. With 2 arguments, the code between\n"
   "the two given addresses is shown.\n"
   "\n"
   "For example, the following shows a partial disassembly\n"
   "listing of a function called \'print\':\n"
   "\n"
   "pathdb> disassemble\n"
   "0x40054c <print>:       55                      push   %rbp\n"
   "0x40054d <print+1>:     48 89 e5                mov    %rsp, %rbp\n"
   "0x400550 <print+4>:     48 83 c4 e0             add    0xffffffffffffffe0, %rsp\n"
   "0x400554 <print+8>:     89 7d f0                mov    %rdi, -16(%rbp) <stream>\n"
   "0x400557 <print+11>:    48 89 75 f8             mov    %rsi, -8(%rbp) <string>\n"
   "0x40055b <print+15>: *  be 00 00 00 00          mov    0x0, %rsi\n"
   "0x400560 <print+20>:    89 75 e4                mov    %rsi, -28(%rbp) <i>\n"
   "0x400563 <print+23>:    48 63 7d e4             arpl   %di, -28(%rbp) <i>\n"
   "\n"
   "The \'*\' shows the current value of the program counter\n"
   "\'PC\'. The number on the left is the address, followed\n"
   "by the function name and offset. Then follows the actual\n"
   "instructions in hex, then in assembly language. The\n"
   "symbols in angle brackets after the assembly are the\n"
   "local variables that are referenced by the instruction.\n"
   "\n"
   "See Also:\n"
   "x\n"
   ,/* End entry: disassemble */

   /* Begin entry: display */
   "Command display: Print the value of the expression every time the\n"
   "debugger stops the program being debugged.\n"
   "This command is very like the \'print\' command,\n"
   "except it records the command in a special list\n"
   "that causes it to be executed every time the program\n"
   "stops. You would use this command to watch the values\n"
   "of variables as you step through a program.\n"
   "\n"
   "The expression to be printed is evaluated in the\n"
   "context in which the \'display\' command was issued and\n"
   "can therefore refer to local variables. The display is\n"
   "disabled when the local variables go out of scope.\n"
   "\n"
   "See Also:\n"
   "print,undisplay\n"
   ,/* End entry: display */

   /* Begin entry: down */
   "Command down: Move the current stack frame down the stack by the\n"
   "specified number of levels. If the number of levels\n"
   "is unspecified, the stack frame is moved down one level.\n"
   "This moves the \'current frame\' down the stack. Moving\n"
   "down the stack means decreasing the frame number\n"
   "towards 0, or moving to the called functions. You\n"
   "cannot move beyond the bottom of the stack (frame #0).\n"
   "Moving among the stack frames allows you to examine the\n"
   "local variables and registers in all the functions on\n"
   "the stack.\n"
   "\n"
   "See Also:\n"
   "backtrace,up,frame\n"
   ,/* End entry: down */

   /* Begin entry: enable delete */
   "Command delete: Set the disposition so that the breakpoints will\n"
   "be deleted when hit.\n"
   ,/* End entry: enable delete */

   /* Begin entry: enable display */
   "Command display: Enable the named displays.\n"
   ,/* End entry: enable display */

   /* Begin entry: enable once */
   "Command once: Set the disposition so that the breakpoints will\n"
   "be disabled when hit.\n"
   ,/* End entry: enable once */

   /* Begin entry: enable */
   "Command enable: Enable or set the disposition on a set of breakpoints.\n"
   "Subcommands:\n"
   "enable delete: Set the disposition so that the breakpoints will\n"
   "be deleted when hit.\n"
   "enable display: Enable the named displays.\n"
   "enable once: Set the disposition so that the breakpoints will\n"
   "be disabled when hit.\n"
   ,/* End entry: enable */

   /* Begin entry: env */
   "Command env: Show the values of all the environment variables.\n"
   "This command prints the values of all the current\n"
   "environment variables.\n"
   ,/* End entry: env */

   /* Begin entry: file */
   "Command file: Change the file being debugged. If no file is\n"
   "specified, the current file is unloaded.\n"
   "This command makes the debugger change the executable\n"
   "file being debugged to that given. If a file is currently\n"
   "being debugged, it can either be forgotten, or the new\n"
   "file added to the list of files. In either case, the new\n"
   "file becomes current.\n"
   ,/* End entry: file */

   /* Begin entry: finish */
   "Command finish: Continue execution until the current function\n"
   "returns.\n"
   "Continue execution of the program until the\n"
   "current function returns to its caller. In addition,\n"
   "the value returned by the function (if it is not void)\n"
   "will be printed and saved to the value history.\n"
   "\n"
   "See Also:\n"
   "run,return,continue\n"
   ,/* End entry: finish */

   /* Begin entry: frame */
   "Command frame: Select the specified frame number or show the current\n"
   "frame. If no frame is specified, information about the\n"
   "current frame is printed.\n"
   "Set the \'current frame\' to that given by the \'frame\n"
   "number\'. If no argument is given,  the current frame is\n"
   "printed to the screen.  This is similar to the \'up\' and\n"
   "\'down\' commands except it moves directly to the frame.\n"
   "\n"
   "See Also:\n"
   "up,down,backtrace\n"
   ,/* End entry: frame */

   /* Begin entry: handle */
   "Command handle: Specify how signals are to be handled when raised by the\n"
   "program being debugged. If the signal-number is \'all\',\n"
   "then all signals are handled in the specified manner.\n"
   "When signals are received by the program being debugged,\n"
   "they are passed up to the debugger.  The debugger needs\n"
   "to be told what to do with them.  For each signal, the\n"
   "choice is:\n"
   "   1. Print the reception of the signal to the screen\n"
   "   (\'print\' option)\n"
   "   2. Pass the signal back to the program being debugged\n"
   "   (\'pass\' option)\n"
   "   3. Stop the debugger (\'stop\' option)\n"
   "A signal has a name (see /usr/include/bits/signum.h).\n"
   "This name should be used  to identify which signal the\n"
   "command will apply to.  You can also use a signal number\n"
   "or the text \'all\' (no quotes) to specify all signals. You\n"
   "can then specify what to do with the signal using the options.\n"
   "More than one option can be used on the same command.\n"
   ,/* End entry: handle */

   /* Begin entry: hbreak */
   "Command hbreak: Set a hardware-assisted breakpoint at the specified location.\n"
   "If no location is given, the current location is used.\n"
   "This command is very similar to the \'break\' command but it\n"
   "creates a hardware assisted breakpoint (using the debug\n"
   "registers of the processor) instead of a software breakpoint.\n"
   "There is a limited number of debug registers available (four\n"
   "on current architectures), so this command should be used\n"
   "sparingly.\n"
   "\n"
   "See Also:\n"
   "break\n"
   ,/* End entry: hbreak */

   /* Begin entry: history */
   "Command history: Show all the commands typed by the user.\n"
   "Print a list of all the commands typed by the user.\n"
   "This is not just for the current session, but since\n"
   "the debugger was first run. The commands are saved.\n"
   ,/* End entry: history */

   /* Begin entry: if */
   "Command if: Execute a sequence of commands if the expression evaluates\n"
   "to non-zero.\n"
   "The expression must be on the same line as the \'if\' command.\n"
   "The commands to execute are entered, one per line, terminated\n"
   "by \'end\' on its own.  The \'else\' command allows the else limb\n"
   "of the \'if\' to be specified.  The \'if\' limb is executed only\n"
   "if the expression evaluates to non-zero, otherwise the \'else\'\n"
   "limb (if it exists) is executed.\n"
   "\n"
   "See Also:\n"
   "while\n"
   ,/* End entry: if */

   /* Begin entry: ignore */
   "Command ignore: Set the ignore-count for the specified breakpoint. If\n"
   "no breakpoint is specified, the last breakpoint set is used.\n"
   "When a breakpoint it hit by the program, a counter is\n"
   "incremented keeping track of the number of times it has\n"
   "been hit.  This command allows the user to specify that\n"
   "the first \'n\' times the breakpoint is hit, the breakpoint\n"
   "should be ignored and have no affect on the program.  The\n"
   "condition expression and commands are not executed if the\n"
   "breakpoint is ignored.\n"
   "\n"
   "\n"
   "See Also:\n"
   "break,condition,commands\n"
   ,/* End entry: ignore */

   /* Begin entry: info address */
   "Command address: Show where the specified symbol is stored.\n"
   ,/* End entry: info address */

   /* Begin entry: info all-registers */
   "Command all-registers: Show the current values of all registers.\n"
   ,/* End entry: info all-registers */

   /* Begin entry: info args */
   "Command args: Show the values of all the arguments to\n"
   "the current function.\n"
   ,/* End entry: info args */

   /* Begin entry: info breakpoints */
   "Command breakpoints: Show all breakpoints, watchpoints, or\n"
   "catchpoints.\n"
   ,/* End entry: info breakpoints */

   /* Begin entry: info catch */
   "Command catch: Show the exceptions that can be caught within\n"
   "the current frame.\n"
   ,/* End entry: info catch */

   /* Begin entry: info copying */
   "Command copying: Show the copyright information for the debugger.\n"
   ,/* End entry: info copying */

   /* Begin entry: info display */
   "Command display: Show the expressions printed when the program\n"
   "hits a breakpoint or otherwise stops execution.\n"
   ,/* End entry: info display */

   /* Begin entry: info frame */
   "Command frame: Show information on the current stack frame.\n"
   ,/* End entry: info frame */

   /* Begin entry: info functions */
   "Command functions: List all function names.\n"
   ,/* End entry: info functions */

   /* Begin entry: info line */
   "Command line: Show information about the current line.\n"
   ,/* End entry: info line */

   /* Begin entry: info locals */
   "Command locals: Show the names and values of all the\n"
   "variables local to the current function.\n"
   ,/* End entry: info locals */

   /* Begin entry: info proc */
   "Command proc: Show information about the running process.\n"
   ,/* End entry: info proc */

   /* Begin entry: info program */
   "Command program: Show the status of the program begin debugged.\n"
   ,/* End entry: info program */

   /* Begin entry: info registers */
   "Command registers: Show the values of the machine registers or,\n"
   "if an argument is supplied, the contents of\n"
   "the named register.\n"
   ,/* End entry: info registers */

   /* Begin entry: info scope */
   "Command scope: List the variables in the named scope.\n"
   ,/* End entry: info scope */

   /* Begin entry: info signals */
   "Command signals: Show how the debugger handles signals caught\n"
   "by the debugged program.\n"
   ,/* End entry: info signals */

   /* Begin entry: info source */
   "Command source: Show information about the current source file.\n"
   ,/* End entry: info source */

   /* Begin entry: info sources */
   "Command sources: Show the source files in the program.\n"
   ,/* End entry: info sources */

   /* Begin entry: info stack */
   "Command stack: Show a stack backtrace of current position.\n"
   ,/* End entry: info stack */

   /* Begin entry: info symbol */
   "Command symbol: Show what symbol is at the specified address.\n"
   ,/* End entry: info symbol */

   /* Begin entry: info threads */
   "Command threads: List all the currently running threads.\n"
   ,/* End entry: info threads */

   /* Begin entry: info variables */
   "Command variables: List all global and static variables.\n"
   ,/* End entry: info variables */

   /* Begin entry: info warranty */
   "Command warranty: Show the warranty information.\n"
   ,/* End entry: info warranty */

   /* Begin entry: info watchpoints */
   "Command watchpoints: Show all breakpoints, watchpoints,\n"
   "and catchpoints.\n"
   ,/* End entry: info watchpoints */

   /* Begin entry: info */
   "Command info: Provide information on the named entity.\n"
   "On its own, this command prints information about\n"
   "all its subcommands.\n"
   "\n"
   "Subcommands:\n"
   "info address: Show where the specified symbol is stored.\n"
   "info all-registers: Show the current values of all registers.\n"
   "info args: Show the values of all the arguments to\n"
   "the current function.\n"
   "info breakpoints: Show all breakpoints, watchpoints, or\n"
   "catchpoints.\n"
   "info catch: Show the exceptions that can be caught within\n"
   "the current frame.\n"
   "info copying: Show the copyright information for the debugger.\n"
   "info display: Show the expressions printed when the program\n"
   "hits a breakpoint or otherwise stops execution.\n"
   "info frame: Show information on the current stack frame.\n"
   "info functions: List all function names.\n"
   "info line: Show information about the current line.\n"
   "info locals: Show the names and values of all the\n"
   "variables local to the current function.\n"
   "info proc: Show information about the running process.\n"
   "info program: Show the status of the program begin debugged.\n"
   "info registers: Show the values of the machine registers or,\n"
   "if an argument is supplied, the contents of\n"
   "the named register.\n"
   "info scope: List the variables in the named scope.\n"
   "info signals: Show how the debugger handles signals caught\n"
   "by the debugged program.\n"
   "info source: Show information about the current source file.\n"
   "info sources: Show the source files in the program.\n"
   "info stack: Show a stack backtrace of current position.\n"
   "info symbol: Show what symbol is at the specified address.\n"
   "info threads: List all the currently running threads.\n"
   "info variables: List all global and static variables.\n"
   "info warranty: Show the warranty information.\n"
   "info watchpoints: Show all breakpoints, watchpoints,\n"
   "and catchpoints.\n"
   ,/* End entry: info */

   /* Begin entry: kill */
   "Command kill: Kill the program being debugged.\n"
   "This kills the process containing the program being\n"
   "debugged.  Once killed, you cannot examine the memory\n"
   "of the process or do anything that requires an active\n"
   "process.\n"
   "\n"
   "See Also:\n"
   "run\n"
   ,/* End entry: kill */

   /* Begin entry: list */
   "Command list: List the source lines at the specified locations.\n"
   "List source code. If no arguments, list the lines\n"
   "around the current location, or the last place listed.\n"
   "A sequence of \'list\' commands with no arguments lists\n"
   "successive lines in the file.\n"
   "\n"
   "With one argument, list the lines around the specified\n"
   "location.  See \'Locations\' for information on specifying\n"
   "locations.  With two arguments, list from the first to\n"
   "the second location (they must be in the same file).\n"
   "\n"
   "See Also:\n"
   "Locations\n"
   ,/* End entry: list */

   /* Begin entry: memdump */
   "Command memdump: Dump the address specified in hex and ASCII.\n"
   "This is a simple memory dumper that takes an address\n"
   "and optional size (default 128 bytes) and dumps the\n"
   "contents of the memory in hex and ASCII.\n"
   "Here is an example:\n"
   "\n"
   "\n"
   "pathdb> memdump main\n"
   "\n"
   "00400F48 14 08 00 00 48 8D 7D C0 48 8D 75 E0 E8 E7 07 00  ....H.}.H.u.....\n"
   "00400F58 00 48 8D 7D E0 E8 0C 08 00 00 48 8D 7D B0 E8 55  .H.}......H.}..U\n"
   "\n"
   "\n"
   "\n"
   "See Also:\n"
   "x\n"
   ,/* End entry: memdump */

   /* Begin entry: next */
   "Command next: Step the program being debugged by a number of\n"
   "lines, stepping over called functions. If no\n"
   "number is specified, then step one line.\n"
   "Single the step the program by a number of lines. If the\n"
   "argument is omitted, the program is stepped by one line.\n"
   "If the lines contain calls to functions, these are stepped\n"
   "over and not followed. The function is still executed, but\n"
   "the debugger does not stop when it enters the function.\n"
   "\n"
   "See Also:\n"
   "step,stepi,nexti,continue\n"
   ,/* End entry: next */

   /* Begin entry: nexti */
   "Command nexti: Step the program being debugged by a number of\n"
   "instructions, stepping over called functions.\n"
   "If no number is specified, step one instruction.\n"
   "Step the program by a number of machine instructions\n"
   "(default 1). If the instructions contain \'call\'\n"
   "instructions these are stepped over. They are still\n"
   "executed but the debugger will not stop when it\n"
   "enters them.\n"
   "\n"
   "See Also:\n"
   "step,stepi,next,continue\n"
   ,/* End entry: nexti */

   /* Begin entry: output */
   "Command output: Print the value of the expression with no\n"
   "line feed and do not insert the value into\n"
   "a debugger variable.\n"
   "Print the value of the expression to the screen with\n"
   "no line feed. The value is not inserted into the value\n"
   "history and thus not recorded in a debugger variable.\n"
   "\n"
   "See Also:\n"
   "print,display\n"
   ,/* End entry: output */

   /* Begin entry: print */
   "Command print: Print the value of the expression and store\n"
   "result in debugger variable.\n"
   "Print the value of the expression in the given format.\n"
   "The syntax of the expression is governed by the language\n"
   "of the current location, so if the location is in a\n"
   "Fortran subroutine then the expression should use\n"
   "Fortran operators and constructs.  The debugger parameter\n"
   "\'language\' controls which language is in effect.\n"
   "\n"
   "See the topic \'Expressions\' for information about\n"
   "the expression operators supported.\n"
   "\n"
   "See Also:\n"
   "Format,Expressions,output,x,display\n"
   ,/* End entry: print */

   /* Begin entry: process */
   "Command process: Switch to another process. If no process is\n"
   "specified, print the current process identifier.\n"
   "The debugger can handle multiple processes at once.\n"
   "The command sets the \'current process\' to that\n"
   "specified by the process number. See the \'processes\'\n"
   "command for information on processes.\n"
   "\n"
   "See Also:\n"
   "processes\n"
   ,/* End entry: process */

   /* Begin entry: processes */
   "Command processes: List all the processes being debugged.\n"
   "Present a list of all the processes owned by\n"
   "the debugger. Here is an example:\n"
   "\n"
   "\n"
   "pathdb> processes\n"
   "Index    PID      State      Command\n"
   "0        28854    READY      /home/pathdb/src/foo\n"
   "\n"
   "\n"
   "Each process has an index, a process id, a state,\n"
   "and the command used to run it. The \'process\'\n"
   "command can be used to set the current process.\n"
   "\n"
   "See Also:\n"
   "process\n"
   ,/* End entry: processes */

   /* Begin entry: ptype */
   "Command ptype: Print the type of the expression.\n"
   "Print the type of the given expression. If the\n"
   "type corresponds to an aggregate (structure or\n"
   "union), then the contents of the aggregate are\n"
   "displayed.  If the expression is a a dynamically\n"
   "typed object (in a C++ inheritance hierarchy),\n"
   "the dynamic type of the object is displayed\n"
   "(unless the \'print object\' parameter is off).\n"
   "For example, in a C++ program:\n"
   "\n"
   "\n"
   "pathdb> ptype y\n"
   "type = Expression *\n"
   "pathdb> ptype *y\n"
   "type = class CallExpression: public Expression {\n"
   "public:\n"
   "int d;\n"
   "void CallExpression();\n"
   "void evaluate();\n"
   "void print();\n"
   "int operator+(int i);\n"
   "int operator-();\n"
   "int operator-(int j);\n"
   "int operator[](int i);\n"
   "CallExpression * operator*();\n"
   "int operator()(int i);\n"
   "void f1(int i);\n"
   "void f1(char c);\n"
   "void dothrow();\n"
   "void dothrow1();\n"
   "}\n"
   "\n"
   "\n"
   "See Also:\n"
   "Expressions,Parameters,print,whatis\n"
   ,/* End entry: ptype */

   /* Begin entry: pwd */
   "Command pwd: Print the current working directory.\n"
   ,/* End entry: pwd */

   /* Begin entry: quit */
   "Command quit: Quit the debugger.\n"
   ,/* End entry: quit */

   /* Begin entry: rerun */
   "Command rerun: Step backwards by a number of commands.\n"
   "This command reruns the program from the beginning,\n"
   "replaying all the (state changing) commands typed\n"
   "by the user up to \'ncommands\' from the current\n"
   "position.  This is an effective \'step backwards\'\n"
   "in the program by a number of commands.\n"
   "\n"
   "See Also:\n"
   "run\n"
   ,/* End entry: rerun */

   /* Begin entry: return */
   "Command return: Return from the current function with the value\n"
   "specified.\n"
   "Cause the current function to return, possibly with\n"
   "a value. The value is specified by the expression\n"
   "argument and must match the return type of the function.\n"
   "\n"
   "See Also:\n"
   "finish\n"
   ,/* End entry: return */

   /* Begin entry: run */
   "Command run: Run the program being debugged with specified\n"
   "arguments.\n"
   "Run the program from the beginning, optionally passing\n"
   "arguments to it. If the command has no arguments then\n"
   "the previous set of arguments are used (or none if there\n"
   "were none). All breakpoints that currently exist in the\n"
   "program will be reinstated and the program will begin\n"
   "execution from the beginning.\n"
   "\n"
   "See Also:\n"
   "cont,step,kill,next\n"
   ,/* End entry: run */

   /* Begin entry: rwatch */
   "Command rwatch: Create a watchpoint for a read of the specified\n"
   "location.\n"
   "This command creates a watchpoint that will trigger when\n"
   "the specified location is read by the program.The location\n"
   "is an expression that contains variables or represents\n"
   "an address. When the variables or address are read, the\n"
   "program will stop.\n"
   "\n"
   "Watchpoints are hardware assisted unless there is no\n"
   "hardware support for them or there are no available debug\n"
   "registers. A hardware watchpoint is much faster than a\n"
   "software watchpoint.\n"
   "\n"
   "See Also:\n"
   "watch,awatch,break\n"
   ,/* End entry: rwatch */

   /* Begin entry: set args */
   "Command args: Set the arguments to be passed to program being debugged.\n"
   ,/* End entry: set args */

   /* Begin entry: set variable */
   "Command variable: Set the value of a program variable.\n"
   ,/* End entry: set variable */

   /* Begin entry: set */
   "Command set: Set the value of control parameters or program variables.\n"
   "Subcommands:\n"
   "set args: Set the arguments to be passed to program being debugged.\n"
   "set variable: Set the value of a program variable.\n"
   ,/* End entry: set */

   /* Begin entry: setenv */
   "Command setenv: Set or print an environment variable.\n"
   "With no args, print the environment variables.\n"
   "With one or two args, set the named environment\n"
   "variable to the given value.\n"
   ,/* End entry: setenv */

   /* Begin entry: shell */
   "Command shell: Execute the rest of the line as a shell command.\n"
   "With no arguments, spawn an interactive shell.\n"
   "The shell spawned is that specified in the $SHELL\n"
   "environment variable (default /bin/sh).\n"
   "\n"
   ,/* End entry: shell */

   /* Begin entry: show version */
   "Command version: Show the version of the debugger.\n"
   ,/* End entry: show version */

   /* Begin entry: show */
   "Command show: Show the values of debugger parameters.\n"
   "Subcommands:\n"
   "show version: Show the version of the debugger.\n"
   ,/* End entry: show */

   /* Begin entry: source */
   "Command source: Execute debugger commands from the specified file.\n"
   ,/* End entry: source */

   /* Begin entry: step */
   "Command step: Step the program being debugged by a number of\n"
   "lines, stepping into called functions. If no\n"
   "number is specified, then step one line.\n"
   "Cause the program to step forward by the specified\n"
   "number of lines. If no argument is given, the program\n"
   "steps one line. If the lines being stepped contain\n"
   "calls to functions, the functions are \'stepped into\'.\n"
   "\n"
   "See Also:\n"
   "next,stepi,nexti,cont\n"
   ,/* End entry: step */

   /* Begin entry: stepi */
   "Command stepi: Step the program being debugged by a number of\n"
   "instructions, following called functions. If no\n"
   "number is specified, then step one function.\n"
   "Cause the program to step number of machine instructions.\n"
   "Like the \'step\' command, if the argument is omitted, one\n"
   "machine instruction is executed. If the instructions being\n"
   "stepped include \'call\' instructions, the call is taken.\n"
   "\n"
   "See Also:\n"
   "next,step,nexti,cont\n"
   ,/* End entry: stepi */

   /* Begin entry: target core */
   "Command core: Attach to a core file as a target.\n"
   ,/* End entry: target core */

   /* Begin entry: target child */
   "Command child: Use a UNIX child process as a target.\n"
   ,/* End entry: target child */

   /* Begin entry: target exec */
   "Command exec: Use an executable file as a target (same as\n"
   "file command).\n"
   ,/* End entry: target exec */

   /* Begin entry: target */
   "Command target: Specify a target.\n"
   "Subcommands:\n"
   "target core: Attach to a core file as a target.\n"
   "target child: Use a UNIX child process as a target.\n"
   "target exec: Use an executable file as a target (same as\n"
   "file command).\n"
   ,/* End entry: target */

   /* Begin entry: tbreak */
   "Command tbreak: Set a temporary breakpoint at the specified location.\n"
   "A temporary breakpoint is a breakpoint with a disposition\n"
   "set to \'del\'. It will be deleted after it is hit.\n"
   "\n"
   "See Also:\n"
   "break,thbreak\n"
   ,/* End entry: tbreak */

   /* Begin entry: thbreak */
   "Command thbreak: Set a temporary hardware-assisted breakpoint at\n"
   "the specified location.\n"
   "Like \'tbreak\', except that the hardware debug registers\n"
   "will be used instead of a software breakpoint.\n"
   "\n"
   "See Also:\n"
   "tbreak\n"
   ,/* End entry: thbreak */

   /* Begin entry: thread */
   "Command thread: Switch to another thread, thus setting the current\n"
   "thread. If no thread is specified, show information\n"
   "on the current thread.\n"
   "The debugger supports programs containing multiple threads.\n"
   "This command allows the user to select a thread as the\n"
   "\'current thread\', to which all subsequent commands apply.\n"
   "Use the command \'info threads\' to see all the threads\n"
   "running in the program.\n"
   ,/* End entry: thread */

   /* Begin entry: unalias */
   "Command unalias: Delete the specified alias.\n"
   "See Also:\n"
   "alias\n"
   ,/* End entry: unalias */

   /* Begin entry: undisplay */
   "Command undisplay: Remove the specified display. If no display\n"
   "is specified, remove all displays.\n"
   "See Also:\n"
   "display\n"
   ,/* End entry: undisplay */

   /* Begin entry: until */
   "Command until: Single step until the location is reached, or\n"
   "until the function returns. If no location is\n"
   "specified, then step one line.\n"
   "If no arguments, single step the program until the\n"
   "current function returns. With one argument, single\n"
   "step until the location specified has been reached.\n"
   "\n"
   "See Also:\n"
   "Locations,step,finish\n"
   ,/* End entry: until */

   /* Begin entry: up */
   "Command up: Move the current stack frame down the stack by\n"
   "the specified number of levels. If the number\n"
   "of levels is unspecified, move the stack up one\n"
   "level.\n"
   "Moving up the stack means increasing the frame number.\n"
   "The bottom of the stack has frame number #0. This\n"
   "command moves the current frame to the calling function.\n"
   "\n"
   "See Also:\n"
   "down,frame,backtrace\n"
   ,/* End entry: up */

   /* Begin entry: watch */
   "Command watch: Create a watchpoint for a change in the value\n"
   "of the specified location.\n"
   "Create a hardware watchpoint (or software watchpoint\n"
   "if there are no debug registers available) that watches\n"
   "for a change in value of the expression. When the value\n"
   "of the expression changes, the debugger will stop the\n"
   "program and display the old and new values of the\n"
   "expression.\n"
   "\n"
   "See Also:\n"
   "awatch,rwatch,break\n"
   ,/* End entry: watch */

   /* Begin entry: whatis */
   "Command whatis: Print the type of the expression.\n"
   "Print the type of the expression. Unlike \'ptype\'\n"
   "the contents of aggregates (structures and unions)\n"
   "are not displayed.\n"
   "\n"
   "See Also:\n"
   "ptype,print\n"
   ,/* End entry: whatis */

   /* Begin entry: while */
   "Command while: Execute a sequence of commands while the\n"
   "expression evaluates to non-zero.\n"
   "The expression must be on the same line as\n"
   "the \'while\' command.  The commands to execute\n"
   "are entered, one per line, terminated by \'end\'\n"
   "on its own.\n"
   ,/* End entry: while */

   /* Begin entry: x */
   "Command x: Examine memory at the specified address,\n"
   "using the format specified.\n"
   "This produces a dump of the program memory in the\n"
   "specified format for the specified number of elements.\n"
   "Typically this will be used to produce a hex dump\n"
   "of memory using a command such as:\n"
   "\n"
   "\n"
   "pathdb> x/10x 0x507520\n"
   "0x507520:   0x00403da0  0x00000000  0x00507088  0x00000000\n"
   "0x507530:   0x00507298  0x00000000  0x0050729c  0x00000000\n"
   "0x507540:   0x0050729c  0x00000000\n"
   "\n"
   "\n"
   "The command parsed as \'examine 0x507520 for 10 elements,\n"
   "each of which is 32 bits and print result in hex\'.  The\n"
   "\'w\' size format code is missing and is default.\n"
   "\n"
   "See Also:\n"
   "print,Formats\n"
   ,/* End entry: x */

   /* Cap the list with NULL */
   NULL
};



/* Lookup table for help entries (allows entry aliasing)  */
/**********************************************************/

pathdb_help_entry_t PATHDB_HELP_TABLE[] = {
   {"help", 0},
   {"Breakpoints", 1},
   {"Running", 2},
   {"Locations", 3},
   {"Commands", 4},
   {"Formats", 5},
   {"Expressions", 6},
   {"Parameters", 7},
   {"advance", 8},
   {"alias", 9},
   {"attach", 10},
   {"backtrace", 11},
   {"break", 12},
   {"call", 13},
   {"catch catch", 14},
   {"catch exec", 15},
   {"catch exit", 16},
   {"catch fork", 17},
   {"catch load", 18},
   {"catch print", 19},
   {"catch start", 20},
   {"catch signal", 21},
   {"catch stop", 22},
   {"catch thread_exit", 23},
   {"catch thread_join", 24},
   {"catch thread_start", 25},
   {"catch throw", 26},
   {"catch unload", 27},
   {"catch vfork", 28},
   {"catch", 29},
   {"cd", 30},
   {"clear", 31},
   {"commands", 32},
   {"condition", 33},
   {"continue", 34},
   {"define", 35},
   {"delete breakpoints", 36},
   {"delete", 37},
   {"detach", 38},
   {"dir", 39},
   {"disable", 40},
   {"disassemble", 41},
   {"display", 42},
   {"down", 43},
   {"enable delete", 44},
   {"enable display", 45},
   {"enable once", 46},
   {"enable", 47},
   {"env", 48},
   {"file", 49},
   {"finish", 50},
   {"frame", 51},
   {"handle", 52},
   {"hbreak", 53},
   {"history", 54},
   {"if", 55},
   {"ignore", 56},
   {"info address", 57},
   {"info all-registers", 58},
   {"info args", 59},
   {"info breakpoints", 60},
   {"info catch", 61},
   {"info copying", 62},
   {"info display", 63},
   {"info frame", 64},
   {"info functions", 65},
   {"info line", 66},
   {"info locals", 67},
   {"info proc", 68},
   {"info program", 69},
   {"info registers", 70},
   {"info scope", 71},
   {"info signals", 72},
   {"info source", 73},
   {"info sources", 74},
   {"info stack", 75},
   {"info symbol", 76},
   {"info threads", 77},
   {"info variables", 78},
   {"info warranty", 79},
   {"info watchpoints", 80},
   {"info", 81},
   {"kill", 82},
   {"list", 83},
   {"memdump", 84},
   {"next", 85},
   {"nexti", 86},
   {"output", 87},
   {"print", 88},
   {"process", 89},
   {"processes", 90},
   {"ptype", 91},
   {"pwd", 92},
   {"quit", 93},
   {"rerun", 94},
   {"return", 95},
   {"run", 96},
   {"rwatch", 97},
   {"set args", 98},
   {"set variable", 99},
   {"set", 100},
   {"setenv", 101},
   {"shell", 102},
   {"show version", 103},
   {"show", 104},
   {"source", 105},
   {"step", 106},
   {"stepi", 107},
   {"target core", 108},
   {"target child", 109},
   {"target exec", 110},
   {"target", 111},
   {"tbreak", 112},
   {"thbreak", 113},
   {"thread", 114},
   {"unalias", 115},
   {"undisplay", 116},
   {"until", 117},
   {"up", 118},
   {"watch", 119},
   {"whatis", 120},
   {"while", 121},
   {"x", 122},
   {NULL, 0}
};

